from tkinter import *
import tkinter.messagebox as ss
savan = Tk()
savan.title('Calculator By Savan')
savan.geometry("400x580")
savan.configure(background = "lightgreen")
savan.resizable(0,0)
# savan.wm_iconbitmap('1.ico')
def cb2() :
     e.set("")
     b4.configure(text = "DEL" , command = cb1)
def sav() :
     e.set(eval(e.get()))
     b4.configure(text = "CLR" , command = cb2)
def cb1(x) :
     e.set(e.get()+x)
def kav() :
     e.set(e.get()[0:-1])
e = StringVar()
e1 = Entry(savan ,bg = "white" , textvariable = e , justify = "right" , font = "lucida 50" , relief = FLAT).place(x = 0 , y = 0 , height = 200 , width = 400)
b1 = Button(text = "7" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b1.place(x=0 , y = 200 , height = 95 , width = 95)
b1.configure(command=lambda:cb1("7"))
b2 = Button(text = "8" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b2.place(x=95 , y = 200 , height = 95 , width = 95)
b2.configure(command=lambda:cb1("8"))
b3 = Button(text = "9" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b3.place(x=190 , y = 200 , height = 95 , width = 95)
b3.configure(command=lambda:cb1("9"))
b4 = Button(text = "DEL",command = kav  ,activebackground = "darkgrey" , font = "comicsansms 14" , bg = "darkgrey" , fg = "white" , relief = "flat")
b4.place(x=285 , y = 200 , height = 71 , width = 95)
b5 = Button(text = "4" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b5.place(x= 0 , y = 295 , height = 95 , width = 95)
b5.configure(command=lambda:cb1("4"))
b6 = Button(text = "5" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b6.place(x=95 , y = 295 , height = 95 , width = 95)
b6.configure(command=lambda:cb1("5"))
b7 = Button(text = "6" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b7.place(x=190 , y = 295 , height = 95 , width = 95)
b7.configure(command=lambda:cb1("6"))
b8 = Button(text = "/" ,activebackground = "darkgrey" , font = "comicsansms 14 bold" , bg = "darkgrey" , fg = "white" , relief = "flat")
b8.place(x=285 , y = 271 , height = 71 , width = 95)
b8.configure(command=lambda:cb1("/"))
b9 = Button(text = "1" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b9.place(x= 0 , y = 390 , height = 95 , width = 95)
b9.configure(command=lambda:cb1("1"))
b10 = Button(text = "2" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b10.place(x=95 , y = 390 , height = 95 , width = 95)
b10.configure(command=lambda:cb1("2"))
b11 = Button(text = "3" ,activebackground = "grey" , font = "lucida 25" , bg = "grey" , fg = "white" , relief = "flat")
b11.place(x=190 , y = 390 , height = 95 , width = 95)
b11.configure(command=lambda:cb1("3"))
b12 = Button(text = "*" ,activebackground = "darkgrey" , font = "comicsansms 28" , bg = "darkgrey" , fg = "white" , relief = "flat")
b12.place(x=285 , y = 342 , height = 71 , width = 95)
b12.configure(command=lambda:cb1("*"))
b13 = Button(text = "." ,activebackground = "grey" , font = "comicsansms 25" , bg = "grey" , fg = "white" , relief = "flat")
b13.place(x= 0 , y = 485 , height = 95 , width = 95)
b13.configure(command=lambda:cb1("."))
b14 = Button(text = "0" ,activebackground = "grey" , font = "comicsansms 25" , bg = "grey" , fg = "white" , relief = "flat")
b14.place(x=95 , y = 485 , height = 95 , width = 95)
b14.configure(command=lambda:cb1("0"))
b15 = Button(text = "=" ,command = sav , activebackground = "grey" , font = "comicsansms 25" , bg = "grey" , fg = "white" , relief = "flat")
b15.place(x=190 , y = 485 , height = 95 , width = 95)
b16 = Button(text = "-" ,activebackground = "darkgrey" , font = "comicsansms 28" , bg = "darkgrey" , fg = "white" , relief = "flat")
b16.place(x=285 , y = 413 , height = 71 , width = 95)
b16.configure(command=lambda:cb1("-"))
b17 = Button(text = "+" ,activebackground = "darkgrey" , font = "comicsansms 23" , bg = "darkgrey" , fg = "white" , relief = "flat")
b17.place(x=285 , y = 484 , height = 96 , width = 95)
b17.configure(command=lambda:cb1("+"))
savan.mainloop()
